"""Initial schema: tickets, runs, steps, tool calls, approvals, knowledge, audit.

Revision ID: 0001
Revises:
Create Date: 2026-10-05

One migration per milestone, never squashed during Phase 1 -- the migration
history is part of the review surface. This is M1: the persistence half of the
skeleton. It creates every table in ``docs/data-model.md`` §2.

The file is hand-written rather than autogenerated so the two dialect-specific
pieces -- ``CREATE EXTENSION IF NOT EXISTS vector`` and the two partial indexes
-- are explicit and guarded, and so ``alembic upgrade head`` runs against SQLite
for the test path as well as against Postgres (ADR-0004).

Postgres-only vs SQLite, and why:

- ``CREATE EXTENSION IF NOT EXISTS vector`` runs only when the dialect is
  postgresql. SQLite has no extensions.
- ``gen_random_uuid()`` server defaults are emitted only on Postgres; on SQLite
  the ORM's Python-side ``uuid.uuid4`` default supplies the value (the app
  always inserts through the ORM).
- The ``hnsw`` vector index is Postgres-only; SQLite serves retrieval from the
  in-memory store.
- The claim and idempotency indexes are partial indexes, which SQLite *does*
  support, so their predicates are emitted on both dialects via
  ``postgresql_where`` and ``sqlite_where``.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import JSONB

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# The claim predicate, built from the domain enum's values. Duplicated as a
# literal here because a migration must be a frozen snapshot of history -- it
# must not import application code that can change under it. The test suite
# asserts this predicate matches ``CLAIMABLE`` today.
_CLAIMABLE = ("classifying", "executing", "planning", "received", "responding", "retrieving")
_CLAIM_WHERE = "status IN (" + ", ".join(f"'{s}'" for s in _CLAIMABLE) + ")"

_IDEMPOTENCY_WHERE = "idempotency_key IS NOT NULL AND status = 'executed'"


def _is_postgres() -> bool:
    """Whether the bound migration connection targets PostgreSQL."""
    return op.get_bind().dialect.name == "postgresql"


def _uuid_server_default() -> sa.TextClause | None:
    """``gen_random_uuid()`` as a server default on Postgres, else nothing."""
    return sa.text("gen_random_uuid()") if _is_postgres() else None


def _json_type() -> sa.types.TypeEngine[object]:
    """``JSONB`` on Postgres, ``JSON`` elsewhere."""
    return sa.JSON().with_variant(JSONB(), "postgresql")


def upgrade() -> None:
    if _is_postgres():
        # pgvector. First operation of the initial migration (docs/data-model.md §5).
        op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    uuid_default = _uuid_server_default()

    op.create_table(
        "tickets",
        sa.Column("id", sa.Uuid(), server_default=uuid_default, nullable=False),
        sa.Column("external_id", sa.Text(), nullable=True),
        sa.Column("subject", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("customer_email", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_tickets"),
        sa.UniqueConstraint("external_id", name="uq_tickets_external_id"),
    )
    op.create_index("ix_tickets_customer_email", "tickets", ["customer_email"])

    op.create_table(
        "agent_runs",
        sa.Column("id", sa.Uuid(), server_default=uuid_default, nullable=False),
        sa.Column("ticket_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("model_provider", sa.String(), nullable=False),
        sa.Column("model_name", sa.String(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_agent_runs"),
        sa.ForeignKeyConstraint(["ticket_id"], ["tickets.id"], name="fk_agent_runs_ticket_id"),
    )
    op.create_index("ix_agent_runs_ticket_id", "agent_runs", ["ticket_id"])
    op.create_index("ix_agent_runs_status", "agent_runs", ["status"])
    # The worker's claim index: partial, so completed/failed runs stay out.
    op.create_index(
        "ix_agent_runs_claimable",
        "agent_runs",
        ["created_at"],
        postgresql_where=sa.text(_CLAIM_WHERE),
        sqlite_where=sa.text(_CLAIM_WHERE),
    )

    op.create_table(
        "agent_steps",
        sa.Column("id", sa.Uuid(), server_default=uuid_default, nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("step_type", sa.String(), nullable=False),
        sa.Column("input", _json_type(), nullable=True),
        sa.Column("output", _json_type(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_agent_steps"),
        sa.ForeignKeyConstraint(["run_id"], ["agent_runs.id"], name="fk_agent_steps_run_id"),
        sa.UniqueConstraint("run_id", "sequence", name="uq_agent_steps_run_id_sequence"),
    )
    op.create_index("ix_agent_steps_run_id", "agent_steps", ["run_id"])

    op.create_table(
        "tool_calls",
        sa.Column("id", sa.Uuid(), server_default=uuid_default, nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("step_id", sa.Uuid(), nullable=True),
        sa.Column("tool_name", sa.String(), nullable=False),
        sa.Column("arguments", _json_type(), nullable=False),
        sa.Column("permission", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("result", _json_type(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column("idempotency_key", sa.String(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_tool_calls"),
        sa.ForeignKeyConstraint(["run_id"], ["agent_runs.id"], name="fk_tool_calls_run_id"),
        sa.ForeignKeyConstraint(["step_id"], ["agent_steps.id"], name="fk_tool_calls_step_id"),
    )
    op.create_index("ix_tool_calls_run_id", "tool_calls", ["run_id"])
    op.create_index("ix_tool_calls_idempotency_key", "tool_calls", ["idempotency_key"])
    # The database-level backstop against a duplicate refund: partial unique.
    op.create_index(
        "uq_tool_calls_idempotency_key_executed",
        "tool_calls",
        ["idempotency_key"],
        unique=True,
        postgresql_where=sa.text(_IDEMPOTENCY_WHERE),
        sqlite_where=sa.text(_IDEMPOTENCY_WHERE),
    )

    op.create_table(
        "approval_requests",
        sa.Column("id", sa.Uuid(), server_default=uuid_default, nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("tool_call_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("risk_explanation", sa.Text(), nullable=False),
        sa.Column("arguments_snapshot", _json_type(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decided_by", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_approval_requests"),
        sa.ForeignKeyConstraint(["run_id"], ["agent_runs.id"], name="fk_approval_requests_run_id"),
        sa.ForeignKeyConstraint(
            ["tool_call_id"], ["tool_calls.id"], name="fk_approval_requests_tool_call_id"
        ),
        sa.UniqueConstraint("tool_call_id", name="uq_approval_requests_tool_call_id"),
    )
    op.create_index("ix_approval_requests_run_id", "approval_requests", ["run_id"])

    op.create_table(
        "knowledge_documents",
        sa.Column("id", sa.Uuid(), server_default=uuid_default, nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("metadata", _json_type(), nullable=False),
        sa.Column("content_hash", sa.String(), nullable=False),
        sa.Column("indexed_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_knowledge_documents"),
        sa.UniqueConstraint("source", name="uq_knowledge_documents_source"),
    )

    op.create_table(
        "knowledge_chunks",
        sa.Column("id", sa.Uuid(), server_default=uuid_default, nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("anchor", sa.Text(), nullable=False),
        sa.Column("heading_path", sa.Text(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        # pgvector on Postgres, JSON on SQLite. The dimension is read at render
        # time by the model's TypeDecorator, so it is not baked in here.
        sa.Column("embedding", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_knowledge_chunks"),
        sa.ForeignKeyConstraint(
            ["document_id"], ["knowledge_documents.id"], name="fk_knowledge_chunks_document_id"
        ),
        sa.UniqueConstraint(
            "document_id", "ordinal", name="uq_knowledge_chunks_document_id_ordinal"
        ),
    )
    op.create_index("ix_knowledge_chunks_document_id", "knowledge_chunks", ["document_id"])
    if _is_postgres():
        op.execute("ALTER TABLE knowledge_chunks ALTER COLUMN embedding TYPE vector(1536)")
        op.execute(
            "CREATE INDEX ix_knowledge_chunks_embedding "
            "ON knowledge_chunks USING hnsw (embedding vector_cosine_ops)"
        )

    op.create_table(
        "citations",
        sa.Column("id", sa.Uuid(), server_default=uuid_default, nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("chunk_id", sa.Uuid(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_citations"),
        sa.ForeignKeyConstraint(["run_id"], ["agent_runs.id"], name="fk_citations_run_id"),
        sa.ForeignKeyConstraint(
            ["document_id"], ["knowledge_documents.id"], name="fk_citations_document_id"
        ),
        sa.ForeignKeyConstraint(
            ["chunk_id"], ["knowledge_chunks.id"], name="fk_citations_chunk_id"
        ),
    )
    op.create_index("ix_citations_run_id", "citations", ["run_id"])

    op.create_table(
        "audit_events",
        sa.Column("id", sa.Uuid(), server_default=uuid_default, nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=True),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("actor", sa.String(), nullable=False),
        sa.Column("payload", _json_type(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_audit_events"),
        sa.ForeignKeyConstraint(["run_id"], ["agent_runs.id"], name="fk_audit_events_run_id"),
    )
    op.create_index("ix_audit_events_run_id", "audit_events", ["run_id"])
    op.create_index("ix_audit_events_event_type", "audit_events", ["event_type"])
    op.create_index("ix_audit_events_created_at", "audit_events", ["created_at"])


def downgrade() -> None:
    op.drop_index("ix_audit_events_created_at", table_name="audit_events")
    op.drop_index("ix_audit_events_event_type", table_name="audit_events")
    op.drop_index("ix_audit_events_run_id", table_name="audit_events")
    op.drop_table("audit_events")

    op.drop_index("ix_citations_run_id", table_name="citations")
    op.drop_table("citations")

    if _is_postgres():
        op.drop_index("ix_knowledge_chunks_embedding", table_name="knowledge_chunks")
    op.drop_index("ix_knowledge_chunks_document_id", table_name="knowledge_chunks")
    op.drop_table("knowledge_chunks")

    op.drop_table("knowledge_documents")

    op.drop_index("ix_approval_requests_run_id", table_name="approval_requests")
    op.drop_table("approval_requests")

    op.drop_index("uq_tool_calls_idempotency_key_executed", table_name="tool_calls")
    op.drop_index("ix_tool_calls_idempotency_key", table_name="tool_calls")
    op.drop_index("ix_tool_calls_run_id", table_name="tool_calls")
    op.drop_table("tool_calls")

    op.drop_index("ix_agent_steps_run_id", table_name="agent_steps")
    op.drop_table("agent_steps")

    op.drop_index("ix_agent_runs_claimable", table_name="agent_runs")
    op.drop_index("ix_agent_runs_status", table_name="agent_runs")
    op.drop_index("ix_agent_runs_ticket_id", table_name="agent_runs")
    op.drop_table("agent_runs")

    op.drop_index("ix_tickets_customer_email", table_name="tickets")
    op.drop_table("tickets")
